export const ContactsConstants = {
  UPDATE_DASHBOARD_DATA: 'contacts/UPDATE_DASHBOARD_DATA',
  CLEAR_USER_STATE: 'contacts/CLEAR_USER_STATE',
  SET_ON_SYNC_FLAG: 'contacts/SET_ON_SYNC_FLAG',
  SET_DASHBOARD_DATA: 'contacts/SET_DASHBOARD_DATA',
  SET_CONTACTS_DATA: 'contacts/SET_CONTACTS_DATA',
  PUSH_CONTACTS_DATA: 'CONTACTS/PUSH_CONTACTS_DATA',
  SET_TABLE_FILTER: 'CONTACTS/SET_TABLE_FILTER',
};
